kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: awx-cluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 9080
    protocol: TCP
  - containerPort: 443
    hostPort: 9443
    protocol: TCP
- role: worker
  extraMounts:
  - hostPath: /tmp/awx-data
    containerPath: /data
- role: worker
  extraMounts:
  - hostPath: /tmp/awx-data
    containerPath: /data
